import CartContextProvider from "@/context/productCartContext";
import ProductContextProvider from "@/context/productContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{margin:'0',padding:'0'}}>
        <CartContextProvider>
          <ProductContextProvider>
            {children}
          </ProductContextProvider>
        </CartContextProvider>

      </body>
    </html>
  );
}
